datastore:
  # Connection string for accessing the Azure Blob Storage
  connection_str: 'DefaultEndpointsProtocol=https;AccountName=freddiemac3796368842;AccountKey=Ill/x3zRIZ3Dmmkt0Xf3unrtwmVbZxx8zE9Z6nh52Ag5ZzD0jaV0Zndv7nziJsBXH1F3qJy7zLJe+AStevryIw==;EndpointSuffix=core.windows.net'
  # Name of the container in the Azure Blob Storage
  container_name: 'azureml-blobstore-77b8f921-69f9-47c4-99b1-e2817b7bae3b'

parameters:
  # Year for the dataset
  year: '2004'
  # Dataset for loan origination
  origination_dataset: 'Orig_Q1_2004'
  # Keyword to identify origination data
  origination_keyword: 'Orig'
  # Dataset for loan performance
  performance_dataset: 'Perf_Q1_2004'
  # Keyword to identify performance data
  performance_keyword: 'Perf'
  # File paths for the origination and performance datasets
  origination_file_path: 'UI/2025-03-23_204519_UTC/historical_data_2004Q1.txt'
  performance_file_path: 'UI/2025-03-23_201805_UTC/historical_data_time_2004Q1.txt'

# List of all columns from the origination data from Freddie Mac
columns: 
  origination:
    - Credit Score
    - First Payment Date
    - First Time Homebuyer Flag
    - Maturity Date
    - MSA
    - MI%
    - No of Units
    - Occupancy Status
    - CLTV
    - DTI Ratio
    - Ori UPB
    - Ori LTV
    - Ori Interest Rate
    - Channel
    - PPM Flag
    - Amortization Type
    - Property State
    - Property Type
    - Postal Code
    - Loan Seq Number
    - Loan Purpose
    - Ori Loan Term
    - Number of Borrowers
    - Seller Name
    - Servicer Name
    - Super Conforming Flag
    - Pre-relief Refinance Loan Seq Number
    - Program Indicator
    - Relief Refinance Indicator
    - Property Valuation Method
    - I/O Indicator
    - MI Cancellation Indicator

  # List of relevant columns extracted from the origination data
  relevant_origination_data:
    - Loan Seq Number
    - Credit Score
    - First Time Homebuyer Flag
    - No of Units
    - Occupancy Status
    - CLTV
    - DTI Ratio
    - Ori UPB
    - Ori Interest Rate
    - Channel
    - Amortization Type
    - Property State
    - Property Type
    - Postal Code
    - Loan Purpose
    - Ori Loan Term
    - Number of Borrowers
    - Servicer Name
    - I/O Indicator
    - MI Cancellation Indicator  

  # List of all columns from the performance data from Freddie Mac
  performance:
    - Loan Seq Number
    - Monthly reporting period
    - Current actual UPB
    - Current loan delinquency status
    - Loan age
    - Remaining months to legal maturity
    - Defect settlement data
    - Modification flag
    - Zero balance code
    - ZB effective date
    - Current interest rate
    - current deferred UPB
    - DDLPI
    - MI recoveries
    - Net sale proceeds
    - Non MI recoveries
    - Total expenses
    - Legal costs
    - Maintenance and preservation costs
    - Taxes and insurance
    - Miscellaneous expenses
    - Actual loss calculation
    - Cumulative modification cost
    - Step modification flag
    - Payment deferral
    - ELTV
    - ZB removal UPB
    - Delinquent accrued interest
    - Delinquency due to disaster
    - Borrower assistance status code
    - Current month modification cost
    - Interest bearing UPB  

  # List of relevant columns extracted from the performance data
  relevant_performance_data:
    - Loan Seq Number
    - Current actual UPB
    - Current loan delinquency status
    - Loan age
    - Remaining months to legal maturity
    - Current interest rate

  # List of columns used for anomaly detection
  anomaly_detection:
    - Credit Score
    - CLTV
    - No of Units
    - DTI Ratio
    - Ori UPB
    - Ori Interest Rate
    - Ori Loan Term
    - Number of Borrowers
    - Current actual UPB
    - Current loan delinquency status
    - Loan age
    - Remaining months to legal maturity
    - Current interest rate

  # List of columns for missing value replacement
  missing_value_replacement:
    # Columns to be replaced with mode value
    mode:
      - First Time Homebuyer Flag
      - No of Units
      - Occupancy Status
      - Channel
      - Amortization Type
      - Property State
      - Property Type
      - Loan Purpose
      - Ori Loan Term
      - Number of Borrowers
      - Servicer Name
      - I/O Indicator
      - MI Cancellation Indicator
      - Current actual UPB
      - Current loan delinquency status
      - Postal Code

    # Columns to be replaced with mean value
    mean:
      - Credit Score
      - CLTV
      - DTI Ratio
      - Ori UPB
      - Ori Interest Rate
      - Loan age
      - Current interest rate
      - Remaining months to legal maturity

# Conditions applied for detecting missing values based on Freddie Mac documentation
missing_value_conditions:
  Credit Score: "x > 900"
  CLTV: "x == 999"
  First Time Homebuyer Flag: "pd.to_numeric(x, errors='coerce') == 9"
  DTI Ratio: "pd.to_numeric(x, errors='coerce') == 999"
  Remaining months to legal maturity: "x < 0"
  Channel: "pd.to_numeric(x, errors='coerce') == 9"
  No of Units: "pd.to_numeric(x, errors='coerce') == 99"
  Occupancy status: "pd.to_numeric(x, errors='coerce') == 9"
  Property Type: "pd.to_numeric(x, errors='coerce') == 99"
  Loan Purpose: "pd.to_numeric(x, errors='coerce') == 9"
  Number of Borrowers: "pd.to_numeric(x, errors='coerce') == 99"
  Servicer Name: "pd.to_numeric(x, errors='coerce') == 9"
  Postal Code: "pd.to_numeric(x, errors='coerce') == 0"

# Identifier for loan records
loan_identifier: 'Loan Seq Number'

# Loan delinquency threshold and indicator
loan_delinquency_threshold: 3
loan_delinquency_indicator: ra

# File paths for feature and label datasets
feature_file: data/features.csv
label_file: data/labels.csv

# Data loading parameters
random_seed: 42
test_size_initial: 0.30
test_size_final: 0.50
scaling: MinMaxScaler
device_preference: auto  # auto = 'cuda' if available, else 'cpu'

# Training configuration
training:
  num_epochs: 50
  input_size: 23  # Number of input features
  output_size: 1  # Number of output labels
  hidden_sizes: [2560, 1280, 640, 320, 160, 80, 40, 20, 10, 5]  # Sizes of hidden layers
  initialization: he  # Weight initialization method
  dropout: 0.3  # Dropout rate for regularization

  learning_rate: 0.0002  # Learning rate for the optimizer
  weight_decay: 0.0  # Weight decay for regularization
  pos_weights: [2.0]  # Positive class weights for imbalanced data
  batch_percentage: 0.02  # Percentage of data used in each batch
  scheduler:
    milestones: [10, 25, 50]  # Epochs where learning rate is adjusted
    gamma: 0.1  # Factor by which learning rate is multiplied
  state_start_index: 19
  state_end_index: 70
